### ISSUE TITLE
Compile fails (TS2742)

### ISSUE THREAD

**Issue by renatoliveira** [renatoliveira/apex-test-list#20]
On the declaration of the flags for the command, now TS is complaining about it, for some reason:

```
src/commands/apextests/list.ts:29:26 - error TS2742: The inferred type of 'flags' cannot be named without a reference to '@salesforce/sf-plugins-core/node_modules/@oclif/core/interfaces'. This is likely not portable. A type annotation is necessary.
```

**Comment by mcarvin8** [comment]
These issues tend to happen during dependency upgrades, which is why dependabot is nice so that it will open MRs for you and run your unit/nut tests for you to catch these before merge.

I was able to replicate this locally after upgrading the package.json to match your branch.

Usually this happens if you upgrade packages from one Major version to another. This happened to me recently when I was upgrading my packages to the latest version, which was a new Major release (v1.x.x to v2.x.x).

But this one looks weird since it just went from "@salesforce/sf-plugins-core" 11.3.9 to 11.3.10.

Looking more into this.

**Comment by mcarvin8** [comment]
I was able to "fix" the issue by reverting the typescript dependency to "typescript": "^5.5.4",

I'm not sure why that fixes it, but I was having issues with my other plugin with a newer typescript version, so I'd need to look into the change log.

**Comment by renatoliveira** [comment]
Doing that seems to work to fix tests locally, but then when using `yarn prepack`, the error still happens! Really weird!

**Comment by renatoliveira** [comment]
Had some other issues with Yarn and the local install but damn I think I solved it now. lol
